/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Clinically.Kinde.Authentication.ManagementApi.Model
{
    /// <summary>
    /// GetEnvironmentFeatureFlagsResponse
    /// </summary>
    [DataContract(Name = "get_environment_feature_flags_response")]
    public partial class GetEnvironmentFeatureFlagsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEnvironmentFeatureFlagsResponse" /> class.
        /// </summary>
        /// <param name="code">Response code..</param>
        /// <param name="message">Response message..</param>
        /// <param name="featureFlags">The environment&#39;s feature flag settings..</param>
        /// <param name="nextToken">Pagination token..</param>
        public GetEnvironmentFeatureFlagsResponse(string code = default(string), string message = default(string), Dictionary<string, GetOrganizationFeatureFlagsResponseFeatureFlagsValue> featureFlags = default(Dictionary<string, GetOrganizationFeatureFlagsResponseFeatureFlagsValue>), string nextToken = default(string))
        {
            this.Code = code;
            this.Message = message;
            this.FeatureFlags = featureFlags;
            this.NextToken = nextToken;
        }

        /// <summary>
        /// Response code.
        /// </summary>
        /// <value>Response code.</value>
        [DataMember(Name = "code", EmitDefaultValue = false)]
        public string Code { get; set; }

        /// <summary>
        /// Response message.
        /// </summary>
        /// <value>Response message.</value>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// The environment&#39;s feature flag settings.
        /// </summary>
        /// <value>The environment&#39;s feature flag settings.</value>
        [DataMember(Name = "feature_flags", EmitDefaultValue = false)]
        public Dictionary<string, GetOrganizationFeatureFlagsResponseFeatureFlagsValue> FeatureFlags { get; set; }

        /// <summary>
        /// Pagination token.
        /// </summary>
        /// <value>Pagination token.</value>
        [DataMember(Name = "next_token", EmitDefaultValue = false)]
        public string NextToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetEnvironmentFeatureFlagsResponse {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  FeatureFlags: ").Append(FeatureFlags).Append("\n");
            sb.Append("  NextToken: ").Append(NextToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
