/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Clinically.Kinde.Authentication.ManagementApi.Model
{
    /// <summary>
    /// ReplaceRedirectCallbackURLsRequest
    /// </summary>
    [DataContract(Name = "replaceRedirectCallbackURLs_request")]
    public partial class ReplaceRedirectCallbackURLsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplaceRedirectCallbackURLsRequest" /> class.
        /// </summary>
        /// <param name="urls">Array of callback urls..</param>
        public ReplaceRedirectCallbackURLsRequest(List<string> urls = default(List<string>))
        {
            this.Urls = urls;
        }

        /// <summary>
        /// Array of callback urls.
        /// </summary>
        /// <value>Array of callback urls.</value>
        [DataMember(Name = "urls", EmitDefaultValue = false)]
        public List<string> Urls { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReplaceRedirectCallbackURLsRequest {\n");
            sb.Append("  Urls: ").Append(Urls).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
